### ISSUE TITLE
Migrate idenplane-java to Spring Boot 4 + Spring Security 7

### ISSUE THREAD

**Issue by Islamawad132** [idenplane/idenplane#1468]
Tracking issue for the Spring Boot 4 / Spring Security 7 migration of `packages/idenplane-java`. Dependabot proposed both as grouped PRs (#1463, #1464) once #1456 landed the BOM grouping; both fail `Java SDK` and are being closed in favour of this, because neither is a dependency bump.

## Current state

```
java.version                17
spring-boot-*               3.5.15   (moved as a family in #1462)
spring-security-*           6.5.10 / 6.5.11
```

## What actually breaks — two separate failures, from three CI runs

**1. Boot 4 removes `TestRestTemplate`** (#1463)

```
SpringBootSampleApplicationTests.java:[7,48]
  package org.springframework.boot.test.web.client does not exist
SpringBootSampleApplicationTests.java:[54,19] cannot find symbol: class TestRestTemplate
```

Contained and mechanical — one test file, three call sites, swap for the Framework 7 replacement.

**2. Security 7 breaks the authorities mapping** (#1445, and again in #1464)

```
SpringBootSampleApplicationTests.meEndpoint_returnsSubjectAndAuthoritiesForAValidToken:89
```

Line 89 is:

```java
assertThat((List<String>) response.getBody().get("authorities")).contains("ROLE_user");
```

This one is **not** a test problem. It says a valid token no longer produces `ROLE_user`, which points at `IdenplaneAuthoritiesConverter` / `IdenplaneAutoConfiguration` in `idenplane-java-spring/src/main/java/` — library code, not sample code.

## Why this isn't being rushed

This is an **identity SDK**. A subtly wrong role-to-authority mapping is a security defect that a green build will happily ship: the endpoint still answers 200, the authorities are just wrong. It needs someone to read what changed in Security 7's resource-server authority conversion and decide deliberately, not a dependency-cleanup pass.

## Scope when picked up

- [ ] `IdenplaneAuthoritiesConverter` — establish what Security 7 changed, and whether the SDK's contract should follow it or preserve current behaviour
- [ ] `IdenplaneAutoConfiguration` — resource-server config surface
- [ ] `SpringBootSampleApplicationTests` — `TestRestTemplate` → Framework 7 replacement
- [ ] Move **both** families together — `org.springframework.boot:*` and `org.springframework.security:*`. Boot 4 with security pinned at 6.5.x is the exact skew #1456 exists to prevent
- [ ] `idenplane-java-spring-sample/pom.xml` imports its own `spring-boot-dependencies` BOM — it does not inherit, and gets missed (see #1462)
- [ ] Confirm the Java baseline: this module targets 17

## Meanwhile

`.github/dependabot.yml` ignores `org.springframework.boot:*` and `org.springframework.security:*` majors, so the same red PR isn't re-proposed weekly. **Remove those two ignore blocks as part of this migration** — they reference this issue.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by Islamawad132** [comment]
## Root cause found — and it is not what this issue says

I went back to the actual CI failure on #1464 rather than reasoning from the migration guide. The Spring Security 7 group PR did **not** fail on the authorities mapping. All three tests failed identically, and none of them ran:

```
Caused by: java.lang.NoClassDefFoundError:
  org/springframework/security/web/access/HandlerMappingIntrospectorRequestTransformer
    at ...WebMvcSecurityConfiguration.postProcessBeanDefinitionRegistry
       ~[spring-security-config-6.5.2.jar]
```

**The ApplicationContext never started.** `spring-security-config` was still on **6.5.2** while `spring-security-web` moved to **7.x**, and `HandlerMappingIntrospectorRequestTransformer` was removed from `-web` in 7. The old config module looks for a class the new web module no longer ships.

That is a **version skew**, not an incompatibility with Security 7 — the same class of failure #1456 exists to prevent, arriving through a path grouping does not cover.

### Why grouping did not catch it

`groups: spring-security: "org.springframework.security:*"` correctly moves the four artifacts pinned in `packages/idenplane-java/pom.xml`. But `idenplane-java-spring-sample` **imports the `spring-boot-dependencies` BOM itself** (it needs `idenplane-java` as its parent for reactor resolution, so it cannot also extend `spring-boot-starter-parent`). That BOM manages `spring-security-config`, which is **not pinned in the parent** — so Dependabot never proposes it, and it stays wherever the Boot BOM puts it.

The pom already carries a comment describing this exact trap for jackson — `jackson-databind` pinned directly, `jackson-annotations`/`jackson-core` left to the BOM, `ObjectMapper` failing at class-init. Same shape, different artifact.

### What actually needs doing

My earlier framing was wrong on both counts, so the checklist changes:

- [ ] **`spring-security-config` is unpinned.** It reaches the sample only through the Boot BOM. Pin it alongside its four siblings so the family genuinely moves as one — this is the real fix, and it is small.
- [ ] Re-test Security 7 **after** that pin. The authorities mapping may be entirely fine; there is currently **no evidence either way**, because the context never got far enough to exercise it.
- [ ] `TestRestTemplate` removal in Boot 4 (from #1463) is real and unrelated — one test file, three call sites.
- [ ] Boot 4 + Security 7 still need to move together, and this module targets Java 17.

### Corrections to this issue

The claim that "Security 7 breaks the authorities mapping" came from reading `SpringBootSampleApplicationTests:89` in #1445's output as an assertion failure. It was a context-load failure surfacing at that line. `IdenplaneAuthoritiesConverter` and `IdenplaneAutoConfiguration` are **not** known to be broken.

Also worth recording: `JwtAuthenticationConverter.setJwtGrantedAuthoritiesConverter(Converter<Jwt, Collection<GrantedAuthority>>)` still exists unchanged in Spring Security 7.0.7 — [API docs](https://docs.spring.io/spring-security/reference/7.0/api/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.html). The SDK's converter signature needs no change on that front.

The `.github/dependabot.yml` ignore blocks (from #1469) stay until this lands.

**Comment by Islamawad132** [comment]
## Probe result: the converter is still not the problem

#1497 moved all five `org.springframework.security` artifacts to 7.1.0 together — possible for the first time now that #1496 pinned `spring-security-config`. `Java SDK` failed, and this time the failure is **real code executing**, not a resolution error:

```
NoSuchMethodError:
  void org.springframework.http.RequestEntity.<init>(HttpHeaders, HttpMethod, URI)
    at ...IdenplaneAutoConfiguration.idenplaneJwtDecoder
```

`RequestEntity` is **spring-web**, not Spring Security. Resolved versions in that run:

| | |
|---|---|
| spring-security-* | **7.1.0** |
| spring-core / spring-web / spring-context | **6.2.19** |
| spring-boot | 3.5.16 |

Spring Security 7 is compiled against **Spring Framework 7**, whose `RequestEntity` constructor signature differs. Security 7 on Framework 6.2 is simply not a supported combination — `NimbusJwtDecoder.withIssuerLocation(...)` fetches the OIDC metadata document, hits the constructor Framework 6 doesn't have, and the decoder bean dies.

## So, three failures, three different causes, and none of them the converter

| attempt | cause |
|---|---|
| #1445 | one artifact moved alone → context failed |
| #1464 | `spring-security-config` left behind → `NoClassDefFoundError` |
| #1497 | Framework left behind → `NoSuchMethodError` |

Every one was version skew at a different layer. **`IdenplaneAuthoritiesConverter` has still never been executed under Security 7** — the context has never survived long enough to reach it. There remains no evidence it is broken, and [`setJwtGrantedAuthoritiesConverter`'s signature is unchanged in 7.0.7](https://docs.spring.io/spring-security/reference/7.0/api/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationConverter.html).

## What this means for the migration

Security 7 **cannot** be adopted on its own. It requires Framework 7, which arrives with **Spring Boot 4** — so the ignore rules from #1469 are correctly scoped: these two majors have to move in one PR, as one change.

Corrected sequence for whoever picks this up:

- [ ] Bump `spring-boot-*` → 4.x **and** `spring-security-*` → 7.x in the same commit. `spring-boot-dependencies` in the sample's pom moves with them, which is what brings Framework 7 in.
- [ ] Fix `TestRestTemplate` in `SpringBootSampleApplicationTests` — removed in Boot 4. One file, three call sites. Still the only *confirmed* source change.
- [ ] **Then** find out whether the converter needs anything. It is entirely possible the answer is no.
- [ ] Confirm the Java baseline: this module targets 17; check what Boot 4 requires.
- [ ] Remove the two ignore blocks in `.github/dependabot.yml` as part of that PR.

#1497 has served its purpose and is closed. #1496 (the `spring-security-config` pin) is merged and stands on its own — it is what made this diagnosis possible.
